// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationDataAcces.Models;

namespace ReservatiosDataAcces.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210309022324_InitialMigration1")]
    partial class InitialMigration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReservationDataAcces.Models.Reservation", b =>
                {
                    b.Property<int>("IDReservation")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("ReservationDate");

                    b.Property<string>("ReservationInfo")
                        .IsRequired();

                    b.Property<int>("Voters");

                    b.Property<int>("Votings");

                    b.HasKey("IDReservation");

                    b.HasIndex("ContactName");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ReservationDataAcces.Models.User", b =>
                {
                    b.Property<string>("ContactName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("ContactTypeName")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.HasKey("ContactName");

                    b.HasIndex("ContactTypeName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReservatiosDataAcces.Models.ContactType", b =>
                {
                    b.Property<string>("ContactTypeName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Decription");

                    b.HasKey("ContactTypeName");

                    b.ToTable("ContactTypes");

                    b.HasData(
                        new
                        {
                            ContactTypeName = "Contact_Type_1",
                            Decription = "Contact_Type_1"
                        },
                        new
                        {
                            ContactTypeName = "Contact_Type_2",
                            Decription = "Contact_Type_2"
                        },
                        new
                        {
                            ContactTypeName = "Contact_Type_3",
                            Decription = "Contact_Type_3"
                        });
                });

            modelBuilder.Entity("ReservationDataAcces.Models.Reservation", b =>
                {
                    b.HasOne("ReservationDataAcces.Models.User")
                        .WithMany("Reservations")
                        .HasForeignKey("ContactName")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ReservationDataAcces.Models.User", b =>
                {
                    b.HasOne("ReservatiosDataAcces.Models.ContactType")
                        .WithMany("Users")
                        .HasForeignKey("ContactTypeName")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
